[project]
name = "tensorra"
version = "0.1.0"
description = "Lightweight, performant <i>n</i>-dimensional arrays"
authors = ["Alex Maldonado <alex@oasci.org>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]

[tasks]

[dependencies]
max = ">=24.4.0dev7,<24.5"

[environments]
docs = ["docs"]

[feature.docs.dependencies]
mkdocs = "*"
mkdocs-material = "*"
mkdocs-macros-plugin = "*"
mkdocs-glightbox = "*"
mkdocs-git-revision-date-localized-plugin = "*"
pymdown-extensions = ">=10.9,<11"
mkdocs-gen-files = ">=0.4.0,<0.5"

[feature.docs.pypi-dependencies]
mkdocs-awesome-pages-plugin = ">=2.9.3, <2.10"
material-plausible-plugin = ">=0.2.0, <0.3"
