[project]
name = "tensorra"
version = "0.1.0"
description = "Add a short description here"
authors = ["Alex Maldonado <alex@oasci.org>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]

[tasks]

[dependencies]
max = ">=24.4.0dev7,<24.5"
